basePath: /
info:
  contact:
    email: thiago.pereira.ti@gmail.com
    name: Thiago P. Martinez
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Scrum Poker API
  version: "1.0"
paths:
  /rooms:
    post:
      consumes:
      - application/json
      - application/json
      summary: Create a new room
      tags:
      - Rooms
swagger: "2.0"
