definitions:
  models.Error:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  players.Player:
    properties:
      id:
        type: string
      joined_at:
        type: string
      name:
        type: string
    type: object
  rooms.Room:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  rooms.RoomJoinRequest:
    properties:
      player_name:
        type: string
    type: object
  rooms.RoomJoinResponse:
    properties:
      id:
        type: string
      name:
        type: string
      room:
        $ref: '#/definitions/rooms.Room'
    type: object
  rooms.RoomNewRequest:
    properties:
      name:
        type: string
    type: object
info:
  contact: {}
  title: Scrum Poker API
  version: "1.0"
paths:
  /rooms:
    post:
      consumes:
      - application/json
      parameters:
      - description: Create a new room
        in: body
        name: room
        required: true
        schema:
          $ref: '#/definitions/rooms.RoomNewRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Create a new room
      tags:
      - Rooms
  /rooms/{id}/join:
    post:
      consumes:
      - application/json
      parameters:
      - description: Join a room
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/rooms.RoomJoinRequest'
      - description: Room Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rooms.RoomJoinResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Join a room
      tags:
      - Rooms
  /rooms/{id}/players:
    get:
      parameters:
      - description: Room Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/players.Player'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Get players from a room
      tags:
      - Rooms
swagger: "2.0"
